server:
  port: 8080
  salt: golang
  jwt_secret: golang-jwt
database:
  driver: mysql
  host: host.docker.internal
  port: 3305
  database: gin
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai